# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "bulma"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-test-renderer"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      # Ignore major ES version updates, these typically need manual upgrade work
      - dependency-name: "@elastic/elasticsearch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        versions: [">=9.0.0"]
    groups:
      # Group Babel dependencies together
      babel:
        patterns:
        - "@babel/*"
      # Group Jest dependencies together
      jest:
        patterns:
          - "*jest*"
      # Group i18next depedencies together
      i18next:
        patterns:
          - "i18next"
          - "react-i18next"
      # Group Instantsearch dependencies together
      instansearch:
        patterns:
          - "*instantsearch*"
      # Group redux depedencies together
      redux:
        patterns:
          - "*redux*"
      # Group @typescript-eslint dependencies together
      typescript-eslint:
        patterns:
        - "@typescript-eslint/*"
      # Group Webpack dependencies together
      webpack:
        patterns:
        - "*webpack*

